# Generated by Django 3.1 on 2020-10-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0003_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
