# Generated by Django 3.1 on 2020-10-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0004_placeorder_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='img',
        ),
    ]
